
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
    push:
    #paths:
     # - "MicroserviceConfigServer/**"  
     branches: [ master ]
     
 # pull_request:
   # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set Release version
        id: vars
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
       
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Build with Maven
        run: |
               echo "A initial message"
               cd MicroserviceConfigServer
               mvn -B package --file pom.xml
               cd target
               ls -l
      - name: Build docker image and push to ECR
        run: |
              $(aws ecr get-login --no-include-email --region us-east-1)
              docker --version
              docker build -t ${{secrets.ECR_REPO_NAME}}/microserviceconfigserver:${{env.RELEASE_VERSION}} ./MicroserviceConfigServer
        env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            AWS_REGION: ${{secrets.AWS_REGION}}
        
      - name: Check tag version
        run: |
            echo $RELEASE_VERSION
            echo ${{env.RELEASE_VERSION}}
            echo "AWS_ACCESS_KEY_ID= ${{secrets.AWS_ACCESS_KEY_ID}}"  >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY= ${{secrets.AWS_SECRET_ACCESS_KEY}}" >> $GITHUB_ENV
