# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    #paths:
     # - "MicroserviceConfigServer/**"  
   branches: [ master ]
     
 # pull_request:
   # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        echo "A initial message"
        cd MicroserviceConfigServer
        mvn -B package --file pom.xml
        cd target
        ls -l
    - name: Create docker MicroserviceConfigServer image
      run: docker build -t microservice_configserver:$SHA8 ./MicroserviceConfigServer
      #run: docker build -t ghcr.io/myimage/MicroserviceConfigServer:latest -t ghcr.io/myimage/MicroserviceConfigServer:$SHA8 ./MicroserviceConfigServer
